version: 2

sources:
  - name: bronze
    schema: dataplatform
    tables:
      - name: status_abfrage
      - name: veranstalter
      - name: betriebsstaette
      - name: geraet
      - name: device_assignment
      - name: player
